set_property PACKAGE_PIN W5 [get_ports clk]       
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports left_button_display_data]
set_property IOSTANDARD LVCMOS33 [get_ports left_button_display_data]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets left_button_display_data]
set_property PACKAGE_PIN U18 [get_ports center_button_enable_sort]
set_property IOSTANDARD LVCMOS33 [get_ports center_button_enable_sort]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets center_button_enable_sort]


set_property PACKAGE_PIN E19 [get_ports clk_en]
set_property IOSTANDARD LVCMOS33 [get_ports clk_en] 
set_property PACKAGE_PIN U16 [get_ports finished_sort]
set_property IOSTANDARD LVCMOS33 [get_ports finished_sort]


set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[0]]
set_property PACKAGE_PIN V13 [get_ports instruction_counter[0]]   
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[1]]
set_property PACKAGE_PIN V3 [get_ports instruction_counter[1]]
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[2]]
set_property PACKAGE_PIN W3 [get_ports instruction_counter[2]]
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[3]]
set_property PACKAGE_PIN U3 [get_ports instruction_counter[3]]
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[4]]
set_property PACKAGE_PIN P3 [get_ports instruction_counter[4]]
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[5]]
set_property PACKAGE_PIN N3 [get_ports instruction_counter[5]]
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[6]]
set_property PACKAGE_PIN P1 [get_ports instruction_counter[6]]
set_property IOSTANDARD LVCMOS33 [get_ports instruction_counter[7]]
set_property PACKAGE_PIN L1 [get_ports instruction_counter[7]]

set_property PACKAGE_PIN W7 [get_ports {DisplaySegment[6]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[6]}]
set_property PACKAGE_PIN W6 [get_ports {DisplaySegment[5]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[5]}]
set_property PACKAGE_PIN U8 [get_ports {DisplaySegment[4]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[4]}]
set_property PACKAGE_PIN V8 [get_ports {DisplaySegment[3]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[3]}]
set_property PACKAGE_PIN U5 [get_ports {DisplaySegment[2]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[2]}]
set_property PACKAGE_PIN V5 [get_ports {DisplaySegment[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[1]}]
set_property PACKAGE_PIN U7 [get_ports {DisplaySegment[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplaySegment[0]}]
set_property PACKAGE_PIN U2 [get_ports {DisplayAnode[0]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplayAnode[0]}]
set_property PACKAGE_PIN U4 [get_ports {DisplayAnode[1]}]                    
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplayAnode[1]}]
set_property PACKAGE_PIN V4 [get_ports {DisplayAnode[2]}]               
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplayAnode[2]}]
set_property PACKAGE_PIN W4 [get_ports {DisplayAnode[3]}]          
   set_property IOSTANDARD LVCMOS33 [get_ports {DisplayAnode[3]}]
